import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {authAPI, type AuthDB} from '../server/auth-api';
test('hosted accounts: registration, secure sessions, login, recovery, limits and isolation from local saves',async()=>{
 const sql=new DatabaseSync(':memory:');for(const name of ['0000_game_accounts','0001_game_saves','0002_account_email'])sql.exec(readFileSync(new URL('../drizzle/'+name+'.sql',import.meta.url),'utf8').replaceAll('--> statement-breakpoint',''));
 const db:AuthDB={prepare(query){let values:any[]=[];return {bind(...args){values=args;return this;},async first(){return sql.prepare(query).get(...values)??null;},async run(){return sql.prepare(query).run(...values);}} as any;},async batch(statements){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};
 const origin='https://game.example',password='test-only-strong-password',username='test_rider';let cookie='';const sent:string[]=[];let providerOkay=true;
 const originalFetch=globalThis.fetch;globalThis.fetch=async(_url,init)=>{sent.push(JSON.parse(String(init?.body)).text);return new Response('{}',{status:providerOkay?200:503});};
 const env={DB:db,RESEND_API_KEY:'test-only',ACCOUNT_EMAIL_FROM:'Game <accounts@example.com>',ACCOUNT_SITE_ORIGIN:origin};
 const call=async(action:string,data?:unknown,otherOrigin=origin)=>authAPI(new Request(origin+'/api/account/'+action,{method:data?'POST':'GET',headers:{origin:otherOrigin,'content-type':'application/json',cookie},...(data?{body:JSON.stringify(data)}:{})}),env) as Promise<Response>;
 let res=await call('register',{username,password,email:'rider@example.com',marketingConsent:false});assert.equal(res.status,200);const first=await res.json();assert.equal(first.account.username,username);assert.equal(first.account.email,null);assert.equal(first.account.pendingEmail,'rider@example.com');assert.equal(first.account.marketingConsent,false);assert.equal(first.recovery.length,64);assert.match(res.headers.get('set-cookie')!,/Secure; HttpOnly; SameSite=Strict/);cookie=res.headers.get('set-cookie')!.split(';')[0];
 const verifyToken=new URL(sent.at(-1)!.match(/https:\/\/\S+/)![0]).searchParams.get('account_verify')!;
 assert.equal((await call('email-verify',{token:verifyToken})).status,200);
 assert.equal((await call('email-verify',{token:verifyToken})).status,401);
 assert.equal((await(await call('session')).json()).account.email,'rider@example.com');
 assert.equal((await call('email-consent',{consent:true})).status,200);
 assert.equal((await(await call('session')).json()).account.marketingConsent,true);
 assert.equal((await call('email-consent',{consent:false})).status,200);
 assert.equal((await(await call('session')).json()).account.marketingConsent,false);
 assert.equal((await call('email-reset-request',{email:'unknown@example.com'})).status,200);
 assert.equal((await call('email-reset-request',{email:'rider@example.com'})).status,200);
 const resetToken=new URL(sent.at(-1)!.match(/https:\/\/\S+/)![0]).searchParams.get('account_reset')!;
 const oldSession=cookie;
 res=await call('email-reset',{token:resetToken,password:password+'reset'});assert.equal(res.status,200);
 const reset=await res.json();assert.equal(reset.recovery.length,64);
 assert.equal((await(await call('session')).json()).account,null);
 assert.equal((await call('email-reset',{token:resetToken,password})).status,401);
 cookie=res.headers.get('set-cookie')!.split(';')[0];assert.notEqual(cookie,oldSession);
 assert.equal((await call('email-request',{email:'new@example.com',password:'wrong'})).status,401);
 assert.equal((await call('email-request',{email:'new@example.com',password:password+'reset'})).status,200);
 const changeToken=new URL(sent.at(-1)!.match(/https:\/\/\S+/)![0]).searchParams.get('account_verify')!;
 assert.equal((await call('email-reset-request',{email:'rider@example.com'})).status,200);
 const oldEmailToken=new URL(sent.at(-1)!.match(/https:\/\/\S+/)![0]).searchParams.get('account_reset')!;
 assert.equal((await call('email-verify',{token:changeToken})).status,200);
 assert.equal((await(await call('session')).json()).account.email,'new@example.com');
 assert.equal((await call('email-reset',{token:oldEmailToken,password:password+'stolen'})).status,401);
 assert.equal((await call('email-reset-request',{email:'new@example.com'})).status,200);
 const usableHash=sql.prepare('SELECT reset_token_hash FROM game_accounts WHERE username=?').get(username)!.reset_token_hash;
 providerOkay=false;assert.equal((await call('email-reset-request',{email:'new@example.com'})).status,200);providerOkay=true;
 assert.equal(sql.prepare('SELECT reset_token_hash FROM game_accounts WHERE username=?').get(username)!.reset_token_hash,usableHash);
 const stored=sql.prepare('SELECT * FROM game_accounts').get()!;assert.notEqual(stored.password_hash,password);assert.notEqual(stored.recovery_hash,first.recovery);
 assert.equal((await(await call('session')).json()).account.id,first.account.id);
 assert.equal((await call('register',{username:username.toUpperCase(),password,email:'other@example.com',marketingConsent:true})).status,409);
 assert.equal((await call('logout',{},'https://evil.example')).status,403);
 await call('logout',{});assert.equal((await(await call('session')).json()).account,null);
 assert.equal((await call('login',{username,password:password+'wrong'})).status,401);
 res=await call('login',{username,password:password+'reset'});assert.equal(res.status,200);cookie=res.headers.get('set-cookie')!.split(';')[0];const oldCookie=cookie;
 res=await call('recover',{username,password:password+'new',recovery:reset.recovery});assert.equal(res.status,200);const recovered=await res.json();assert.notEqual(recovered.recovery,reset.recovery);
 assert.equal((await(await call('session')).json()).account,null);cookie=res.headers.get('set-cookie')!.split(';')[0];assert.notEqual(cookie,oldCookie);
 assert.equal((await call('recover',{username,password,recovery:reset.recovery})).status,401);
 sql.prepare('DELETE FROM auth_limits').run();
 assert.equal((await call('email-reset-request',{email:'new@example.com'})).status,200);
 const atomicToken=new URL(sent.at(-1)!.match(/https:\/\/\S+/)![0]).searchParams.get('account_reset')!;
 const originalBatch=db.batch;
 db.batch=async statements=>{sql.exec('BEGIN');try{await statements[0].run();throw Error('simulated database failure');}finally{sql.exec('ROLLBACK');}};
 assert.equal((await call('email-reset',{token:atomicToken,password:password+'atomic'})).status,503);
 assert.equal((await(await call('session')).json()).account.id,first.account.id);
 db.batch=originalBatch;
 res=await call('email-reset',{token:atomicToken,password:password+'atomic'});assert.equal(res.status,200);
 assert.equal((await(await call('session')).json()).account,null);cookie=res.headers.get('set-cookie')!.split(';')[0];
 assert.equal((await call('delete',{password:password+'atomic'})).status,200);assert.equal((await(await call('session')).json()).account,null);
 sql.prepare('DELETE FROM auth_limits').run();
 assert.equal((await call('register',{username:'charizard495',password,email:'other@example.com',marketingConsent:true})).status,409);
 assert.equal((await call('register',{username:'x',password:'short'})).status,400);
 assert.equal((await call('login',{padding:'x'.repeat(3000)})).status,413);
 for(let i=0;i<24;i++)res=await call('login',{username:'different',password});assert.equal(res!.status,429);
 assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM game_accounts').get()!.n,0);sql.close();globalThis.fetch=originalFetch;
});

test('email reset request responds before provider delivery and stores a token only after send succeeds',async()=>{
 const sql=new DatabaseSync(':memory:');
 for(const name of ['0000_game_accounts','0001_game_saves','0002_account_email'])sql.exec(readFileSync(new URL('../drizzle/'+name+'.sql',import.meta.url),'utf8').replaceAll('--> statement-breakpoint',''));
 sql.prepare('INSERT INTO game_accounts(id,username,password_hash,salt,recovery_hash,created,email) VALUES (?,?,?,?,?,?,?)').run('one','rider','hash','salt','recovery',Date.now(),'rider@example.com');
 const db:AuthDB={prepare(query){let values:any[]=[];return {bind(...args){values=args;return this;},async first(){return sql.prepare(query).get(...values)??null;},async run(){return sql.prepare(query).run(...values);}} as any;},async batch(){throw Error('unused');}};
 let completeSend:(response:Response)=>void=()=>{};
 const originalFetch=globalThis.fetch;
 globalThis.fetch=()=>new Promise<Response>(resolve=>{completeSend=resolve;});
 const pending:Promise<unknown>[]=[];
 const env={DB:db,RESEND_API_KEY:'test-only',ACCOUNT_EMAIL_FROM:'Game <accounts@example.com>',ACCOUNT_SITE_ORIGIN:'https://game.example'};
 const call=(email:string)=>authAPI(new Request('https://game.example/api/account/email-reset-request',{method:'POST',headers:{origin:'https://game.example','content-type':'application/json'},body:JSON.stringify({email})}),env,{waitUntil:p=>pending.push(p)});
 try{
  const response=await Promise.race([call('rider@example.com'),new Promise<never>((_,reject)=>setTimeout(()=>reject(Error('waited for provider')),500))]);
  assert.equal(response?.status,200);
  assert.equal(sql.prepare('SELECT reset_token_hash FROM game_accounts WHERE id=?').get('one')!.reset_token_hash,null);
  assert.equal(pending.length,1);
  completeSend(new Response('{}',{status:200}));await pending[0];
  assert.match(String(sql.prepare('SELECT reset_token_hash FROM game_accounts WHERE id=?').get('one')!.reset_token_hash),/^[a-f0-9]{64}$/);
  const unknown=await call('nobody@example.com');assert.deepEqual(await unknown?.json(),await response?.json());
  assert.equal(pending.length,1);
 }finally{globalThis.fetch=originalFetch;sql.close();}
});
