import {chromium} from 'playwright';import assert from 'node:assert/strict';import {writeFileSync,mkdirSync} from 'node:fs';
const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage();await p.goto('http://127.0.0.1:5182');await p.waitForFunction(()=>window.__LAZER?.rider.human);const results=await p.evaluate(async()=>{
const g=window.__LAZER;g.testing(true);g.startSession('outdoor',true);const {terrainHeight,terrainNormal}=await import('/src/park/park.ts');const checks=[];const check=(name,ok,detail)=>{if(!ok)throw Error(name+' '+JSON.stringify(detail));checks.push(name);};
function place(x,z,speed){const s=g.sim;s.reset(0,true);g.advance(.25,{},false);s.normal.copy(terrainNormal(x,z));s.position.set(x,terrainHeight(x,z)+.22/Math.max(.55,s.normal.y),z);s.previousPosition.copy(s.position);s.body.setTranslation(s.position,true);s.yaw=s.previousYaw=0;s.velocity.set(0,0,speed).projectOnPlane(s.normal).normalize().multiplyScalar(speed);s.body.setLinvel(s.velocity,true);s.grounded=true;s.lastGround=s.elapsed;return s;}
for(const stance of ['regular','goofy'])for(const side of [-1,1])for(const lip of [false,true]){
 const s=place(lip?-9:0,lip?25.6:-18,lip?7:0);s.tricks.stance=stance;g.advance(.12,{ry:1},false);g.advance(.025,{rx:side*.75,ry:.75},false);g.advance(.009,{rx:side,ry:0},false);check('gesture starts '+stance+side+lip,Math.abs(s.tricks.bri.target)>6,s.snapshot());const target=s.tricks.bri.target;g.advance(.06,{},false);check('neutral preserves target',s.tricks.bri.target===target);const angle=s.tricks.bri.angle;
 if(!s.grounded&&s.state!=='Bail'){g.advance(.09,{held:{brake:1,pumpGrind:1},lean:side},false);check('mid-trick body flip preserves scooter target',s.tricks.bri.target===target);check('mid-trick scooter movement continues',Math.abs(s.tricks.bri.angle)>Math.abs(angle));check('body flip starts',s.bodyFlip.active);}
}
// Pose endpoint continuity on tilted ramps, and render-rate independence.
const s=place(0,-18,0);s.grounded=false;s.position.y=4;s.previousPosition.copy(s.position);s.pitch=.75;s.tricks.startAir(false);const {RotationChannel}=await import('/src/tricks/tricks.ts');for(const dt of [1/30,1/60,1/120]){s.tricks.bri.angle=2*Math.PI-.001;s.tricks.bri.velocity=1;g.rider.update(s,dt,1);const before=g.rider.scooter.position.clone();s.tricks.bri.angle=2*Math.PI;s.tricks.bri.velocity=0;g.rider.update(s,dt,1);check('tilted catch continuity '+dt,before.distanceTo(g.rider.scooter.position)<.01,before.toArray());}
return checks;});mkdirSync('artifacts/bri-motion',{recursive:true});writeFileSync('artifacts/bri-motion/integration.json',JSON.stringify(results,null,2));console.log(results.length+' Bri gesture, mid-flip and tilted-catch checks passed');}finally{await b.close();}
