import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';
mkdirSync('artifacts/bri-motion',{recursive:true});const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const context=await b.newContext({viewport:{width:1280,height:800},recordVideo:{dir:'artifacts/bri-motion/video',size:{width:1280,height:800}}});try{const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5182');await p.waitForFunction(()=>window.__LAZER?.rider.human);await p.evaluate(()=>{const g=window.__LAZER;g.testing(true);g.startSession('outdoor',true);});const results=[];
for(const stance of ['regular','goofy'])for(const direction of [-1,1])for(const view of ['side','front','gameplay']){
 await p.evaluate(({stance,direction})=>{const g=window.__LAZER,s=g.sim;s.reset(0,true);s.position.set(0,5,0);s.previousPosition.copy(s.position);s.body.setTranslation(s.position,true);s.body.setLinvel({x:0,y:3,z:0},true);s.grounded=false;s.state='Airborne';s.tricks.stance=stance;s.tricks.startAir(false);s.tricks.bri.kick(direction);},{stance,direction});const samples=[];
 for(let frame=0;frame<95;frame++){
  const sample=await p.evaluate(({view,frame})=>{const g=window.__LAZER,s=g.sim;g.advance(1/120,{},true);if(view!=='gameplay'){const c=g.camera.camera;c.position.copy(s.position).add({x:view==='side'?4:2.8,y:1.3,z:view==='side'?.3:3.5});c.lookAt(s.position.x,s.position.y+.9,s.position.z);g.renderer.render(g.park.scene,c);}return {frame,state:s.state,angle:s.tricks.bri.angle,velocity:s.tricks.bri.velocity,position:g.rider.scooter.position.toArray(),phase:g.rider.root.userData.briDebug?.phase};},{view,frame});samples.push(sample);if([9,29,49,69,94].includes(frame))await p.screenshot({path:'artifacts/bri-motion/'+stance+'-'+direction+'-'+view+'-'+frame+'.png'});await p.waitForTimeout(12);
 }
 let maxStep=0;for(let i=1;i<samples.length;i++)maxStep=Math.max(maxStep,Math.hypot(...samples[i].position.map((x,k)=>x-samples[i-1].position[k])));assert(maxStep<.22,'position discontinuity '+maxStep);assert(samples.some(s=>Math.abs(s.angle)>6));results.push({stance,direction,view,maxStep,samples});
}
assert.equal(errors.length,0);writeFileSync('artifacts/bri-motion/samples.json',JSON.stringify(results));console.log('12 continuous in-game Bri/Inward motion captures; neutral input preserves active rotation.');}finally{await context.close();await b.close();}
