import {chromium} from 'playwright';import {mkdirSync,writeFileSync} from 'node:fs';import assert from 'node:assert/strict';
const b=await chromium.launch({executablePath:process.env.CHROME_PATH===undefined?'C:/Program Files/Google/Chrome/Application/chrome.exe':(process.env.CHROME_PATH||undefined),headless:true});
try{const p=await b.newPage({viewport:{width:1280,height:960}});await p.goto('http://127.0.0.1:5180/?map=outdoor');await p.waitForFunction(()=>window.__LAZER?.rider.human);await p.evaluate(()=>window.__LAZER.testing(true));const rows=[];mkdirSync('artifacts/complete-update/poses',{recursive:true});
 for(const pose of ['crouch','grab','finger','bri','inward','manual','walk','run','sit','flip']){
  const row=await p.evaluate(async pose=>{const g=window.__LAZER,s=g.sim;const THREE=await import('/node_modules/.vite/deps/three.js');s.reset(0,true);g.advance(.1);s.grounded= !['grab','finger','bri','inward','flip'].includes(pose);s.tricks.airborne=!s.grounded;
   if(pose==='crouch')s.preload.amount=1;if(pose==='grab'){s.tricks.visualPose='Deck Grab';s.tricks.poseBlend=1;}if(pose==='finger'){s.tricks.fingerTime=.175;s.tricks.fingerHand=1;s.tricks.deck.angle=1.3;s.tricks.deck.velocity=12;}if(pose==='bri'||pose==='inward'){s.tricks.bri.angle=pose==='bri'?Math.PI:-Math.PI;s.tricks.bri.velocity=12;}if(pose==='manual'){s.manual.active=true;s.manual.pitch=.3;}if(pose==='walk'||pose==='run'){s.walking=true;s.running=pose==='run';s.velocity.set(0,0,pose==='run'?5:2);}if(pose==='sit')s.sitting={id:'visual-bench',x:s.position.x,z:s.position.z,seat:1,yaw:0};if(pose==='flip'){s.bodyFlip.active=true;s.bodyFlip.angle=Math.PI;s.pitch=Math.PI;}
   for(let i=0;i<40;i++){s.elapsed+=1/60;g.rider.update(s,1/60,1);}g.rider.root.updateMatrixWorld(true);let finite=true,count=0;const bounds=new THREE.Box3();g.rider.human.group.traverse(o=>{if(o.isSkinnedMesh){o.skeleton.update();const a=o.geometry.attributes.position;for(let i=0;i<a.count;i+=7){const v=new THREE.Vector3().fromBufferAttribute(a,i);o.applyBoneTransform(i,v);finite&&=v.toArray().every(Number.isFinite);bounds.expandByPoint(v);count++;}}});
   const center=g.rider.root.position.clone().add(new THREE.Vector3(0,.85,0)),c=g.camera.camera.clone();c.position.copy(center).add(new THREE.Vector3(1.7,.2,2.9));c.lookAt(center);document.querySelectorAll('body>*:not(canvas)').forEach(e=>e.style.display='none');g.renderer.render(g.park.scene,c);return {pose,finite,count,bounds:bounds.getSize(new THREE.Vector3()).toArray()};},pose);rows.push(row);await p.locator('body>canvas').screenshot({path:`artifacts/complete-update/poses/${pose}.png`});assert.ok(row.finite);assert.ok(row.bounds.every(n=>n<3));
 }writeFileSync('artifacts/complete-update/poses/results.json',JSON.stringify(rows,null,2));console.log(rows);
}finally{await b.close();}
