import {chromium} from 'playwright';import {mkdirSync,writeFileSync} from 'node:fs';import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5180/?map=outdoor');await page.waitForFunction(()=>window.__LAZER?.rider.human);await page.evaluate(()=>window.__LAZER.testing(true));mkdirSync('artifacts/complete-update/characters',{recursive:true});const results=[];
 for(const id of ['rider-01','rider-02','rider-03'])for(const quality of ['low','medium','high']){
  const result=await page.evaluate(async({id,quality})=>{const g=window.__LAZER;g.profile.riderId=id;g.profile.settings.characterQuality=quality;g.rider.applyProfile(g.profile);while(g.rider.human?.id!==id||g.rider.human?.quality!==quality)await new Promise(r=>setTimeout(r,30));await new Promise(r=>setTimeout(r,150));g.advance(.05,{},true);let triangles=0;g.rider.human.group.traverse(o=>{if(o.isMesh)triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;});const center=g.rider.root.position.clone().add(g.sim.position.clone().set(0,.86,0)),c=g.camera.camera.clone();c.position.copy(center).add(g.sim.position.clone().set(1.6,.1,2.4));c.lookAt(center);document.querySelectorAll('body>*:not(canvas)').forEach(e=>e.style.display='none');g.renderer.render(g.rider.root.parent,c);return {id,quality,triangles,position:g.sim.position.toArray(),speed:g.sim.speed};},{id,quality});results.push(result);await page.locator('body>canvas').screenshot({path:`artifacts/complete-update/characters/${id}-${quality}.png`});
 }
 const performance=await page.evaluate(async()=>{const g=window.__LAZER;const gl=g.renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');const samples=[];for(let i=0;i<90;i++){const t=window.performance.now();g.render();gl.finish();samples.push(window.performance.now()-t);}samples.sort((a,b)=>a-b);return {browser:navigator.userAgent,gpu:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'unavailable',viewport:[innerWidth,innerHeight],pixelRatio:g.renderer.getPixelRatio(),quality:g.profile.settings.fidelity,medianMs:samples[45],p95Ms:samples[85],draws:g.renderer.info.render.calls,triangles:g.renderer.info.render.triangles,geometryCount:g.renderer.info.memory.geometries,textureCount:g.renderer.info.memory.textures};});
 writeFileSync('artifacts/complete-update/characters/results.json',JSON.stringify({results,performance,errors},null,2));for(const id of ['rider-01','rider-02','rider-03']){const r=results.filter(v=>v.id===id);assert.ok(r[0].triangles<r[1].triangles&&r[1].triangles<r[2].triangles);}assert.equal(errors.length,0);console.log(results,performance);
}finally{await browser.close();}
