import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';
const b=await chromium.launch({executablePath:process.env.CHROME_PATH===undefined?'C:/Program Files/Google/Chrome/Application/chrome.exe':(process.env.CHROME_PATH||undefined),headless:true});const folder='artifacts/fit-pass/addendum';mkdirSync(folder,{recursive:true});
try{const p=await b.newPage({viewport:{width:1280,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5182/?map=outdoor');await p.waitForFunction(()=>window.__LAZER?.rider.avatar);await p.evaluate(async()=>{window.__LAZER.testing(true);await window.__LAZER.startSession('outdoor',true);});const records=[];
for(const [name,x,z]of [['flat',-9,-18],['quarter',-9,24.5],['box',-2,-3],['rail',9,-11],['slope',52,-16]]){
const r=await p.evaluate(async({name,x,z})=>{const g=window.__LAZER,s=g.sim,{terrainHeight}=await import('/src/park/park.ts');s.reset(0,true);s.position.set(x,terrainHeight(x,z)+.28,z);s.previousPosition.copy(s.position);s.body.setTranslation(s.position,true);s.velocity.set(2,0,3);s.body.setLinvel(s.velocity,true);s.bail('test '+name);const start=g.events.history.filter(e=>e.type==='bail').length;g.advance(10,{},true);const r={name,settled:s.crash?.settled,stable:s.crash?.stable,rest:s.crash?.rest,rider:s.crash?.rider.translation(),scooter:s.crash?.scooter.translation(),canRecover:s.crash?.canRecover,bails:g.events.history.filter(e=>e.type==='bail').length-start};return r;},{name,x,z});records.push(r);await p.screenshot({path:`${folder}/crash-${name}.png`});console.log(r);assert.ok(r.settled);assert.equal(r.bails,0);await p.evaluate(()=>window.__LAZER.advance(.03,{pressed:{hop:true}},true));assert.equal(await p.evaluate(()=>window.__LAZER.sim.walking),true);if(name==='flat'){for(const [stage,time]of [['begin',0],['middle',.35],['standing',.5]]){await p.evaluate(time=>window.__LAZER.advance(time,{},true),time);await p.screenshot({path:`${folder}/get-up-${stage}.png`});}}
}
const skipped=await p.evaluate(()=>{const g=window.__LAZER,s=g.sim;s.reset(0,true);s.position.set(-9,.28,-18);s.previousPosition.copy(s.position);s.body.setTranslation(s.position,true);s.velocity.set(2,0,3);s.bail('skip test');g.advance(.05,{},true);g.advance(.009,{pressed:{hop:true}},true);const first=s.state==='Bail';g.advance(.09,{},true);g.advance(.009,{pressed:{hop:true}},true);return {first,walking:s.walking,removed:!s.crash,immediate:s.getUpTimer===0};});console.log({skipped});assert.ok(Object.values(skipped).every(Boolean));
const items=await p.evaluate(async()=>{const g=window.__LAZER,s=g.sim,w=g.interactions,{emptyInput}=await import('/src/input/input.ts'),{loadProfile}=await import('/src/data/loadout.ts');s.reset(0,true);s.walking=true;g.profile.pockets.entries=[];g.profile.pockets.held=null;const f=()=>emptyInput();w.vend(s,'Soda',s.position.clone());const advance=t=>{for(let i=0;i<t*60;i++){const input=f();if(s.emote)s.emote.time+=1/60;w.update(s,input,1/60);g.rider.update(s,1/60,1);w.render(g.rider);}};advance(.9);const id=g.profile.pockets.held;const received=!!id&&g.profile.pockets.entries.length===1;advance(2);const retained=g.profile.pockets.held===id;const use=f();use.pressed.pushDeck=true;w.update(s,use,.016);advance(2.6);const empty=g.profile.pockets.entries[0]?.state==='empty'&&w.prop.visible;const saved=loadProfile().pockets.entries[0]?.state==='empty';s.walking=false;w.update(s,f(),.016);return {received,retained,empty,saved,stowed:g.profile.pockets.held===null,kept:g.profile.pockets.entries.length===1};});console.log(items);assert.ok(Object.values(items).every(Boolean));writeFileSync(`${folder}/crash-items.json`,JSON.stringify({records,items,errors},null,2));assert.equal(errors.length,0);
}finally{await b.close();}
