import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH===undefined?'C:/Program Files/Google/Chrome/Application/chrome.exe':(process.env.CHROME_PATH||undefined),headless:true});
const folder='artifacts/fit-pass/contracts';mkdirSync(folder,{recursive:true});
try{const page=await browser.newPage({viewport:{width:1280,height:960}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5180/?map=outdoor');await page.waitForFunction(()=>window.__LAZER?.rider.human);await page.evaluate(async()=>{window.__LAZER.testing(true);await window.__LAZER.startSession('outdoor',true);});const records=[];
for(const id of ['rider-01','rider-02','rider-03'])for(const build of ['skinny','regular','chunky'])for(const quality of ['low','medium','high']){
 const r=await page.evaluate(async({id,build,quality})=>{const g=window.__LAZER;g.profile.riderId=id;g.profile.bodyBuild=build;g.profile.settings.characterQuality=quality;g.rider.applyProfile(g.profile);while(g.rider.human?.id!==id||g.rider.human?.bodyBuild!==build||g.rider.human?.quality!==quality)await new Promise(r=>setTimeout(r,20));g.sim.reset(0,true);g.advance(.1,{},false);for(let i=0;i<45;i++)g.rider.update(g.sim,1/60,1);g.rider.applyProfile(g.profile);g.rider.update(g.sim,.016,1);g.rider.root.updateMatrixWorld(true);const THREE=await import('/node_modules/.vite/deps/three.js');let triangles=0;g.rider.human.group.traverse(o=>{if(o.isMesh)triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;});return {id,build,quality,triangles,feet:g.rider.shoes.map(o=>o.position.toArray()),hands:g.rider.hands.map(o=>o.position.toArray()),fit:g.rider.human.group.getObjectByName('Head-fitted helmet').userData.fit,legacyHelmetVisible:g.rider.helmet.visible,scale:g.rider.rider.scale.toArray(),mass:g.sim.body.mass(),forearms:g.rider.forearms.map(o=>o.scale.y)};},{id,build,quality});records.push(r);assert.equal(r.legacyHelmetVisible,false);assert.deepEqual(r.scale,[1,1,1]);assert.ok(r.forearms.every(v=>v<.43));
 if(id==='rider-01'&&quality==='high')for(const [view,offset]of [['front',[0,.05,2.8]],['side',[2.8,.05,0]],['rear',[0,.05,-2.8]]]){await page.evaluate(offset=>{const g=window.__LAZER,c=g.camera.camera.clone(),center=g.rider.root.position.clone();center.y+=.85;c.position.copy(center).add(g.sim.position.clone().fromArray(offset));c.lookAt(center);g.renderer.render(g.park.scene,c);document.querySelectorAll('body>*:not(canvas)').forEach(e=>e.style.display='none');},offset);await page.locator('body>canvas').screenshot({path:`${folder}/${build}-${view}.png`});}
}
for(const id of ['rider-01','rider-02','rider-03'])for(const build of ['skinny','regular','chunky']){const [low,medium,high]=records.filter(r=>r.id===id&&r.build===build);assert.ok(low.triangles<medium.triangles&&medium.triangles<high.triangles);for(const r of [medium,high])for(const key of ['feet','hands','fit','mass'])assert.deepEqual(JSON.parse(JSON.stringify(r[key],(_k,v)=>typeof v==="number"?Math.round(v*1e5)/1e5:v)),JSON.parse(JSON.stringify(low[key],(_k,v)=>typeof v==="number"?Math.round(v*1e5)/1e5:v)));}
assert.equal(errors.length,0);writeFileSync('artifacts/fit-pass/contracts.json',JSON.stringify({records,errors},null,2));console.log('27 rider/build/quality combinations: identical contact, fit and mass; descending geometry detail; repeated customization keeps legacy helmet hidden.');
}finally{await browser.close();}
