import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';
const folder='artifacts/fit-pass/appearance';mkdirSync(folder,{recursive:true});const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{const page=await browser.newPage({viewport:{width:1280,height:960}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5180/?map=outdoor');await page.waitForFunction(()=>window.__LAZER?.rider.human);await page.evaluate(async()=>{const g=window.__LAZER;g.testing(true);await g.startSession('outdoor',true);});const records=[];
for(const build of ['skinny','regular','chunky'])for(const pose of ['stand','shorts','crouch','hoodie','long-sleeve','goofy','manual','grab','bri','finger','push']){
const result=await page.evaluate(async({build,pose})=>{const g=window.__LAZER,s=g.sim;g.profile.bodyBuild=build;g.profile.settings.characterQuality='high';g.profile.settings.stance=pose==='goofy'?'goofy':'regular';g.profile.outfit.top=pose==='hoodie'?'top-hoodie-red':pose==='long-sleeve'?'top-long-sleeve-navy':'top-tee-sand';g.profile.outfit.bottom=pose==='shorts'?'bottom-shorts-black':'bottom-chinos-forest';g.rider.applyProfile(g.profile);await new Promise(r=>setTimeout(r,70));s.reset(0,true);s.tricks.stance=g.profile.settings.stance;g.advance(.10,{},false);if(pose==='crouch'){s.preload.amount=1;s.charge=1;}if(pose==='manual'){s.manual.active=true;s.manual.pitch=.25;}if(pose==='grab'){s.grounded=false;s.tricks.visualPose='Deck Grab';s.tricks.poseBlend=.8;}if(pose==='bri'){s.grounded=false;s.tricks.bri.angle=Math.PI*.85;s.tricks.bri.velocity=12;}if(pose==='finger'){s.grounded=false;s.tricks.fingerTime=.23;s.tricks.fingerHand=1;s.tricks.deck.angle=.65;s.tricks.deck.velocity=12;}if(pose==='push')s.pushTimer=.29;for(let i=0;i<30;i++)g.rider.update(s,1/60,1);g.rider.root.updateMatrixWorld(true);
const THREE=await import('/node_modules/.vite/deps/three.js'),center=g.rider.root.position.clone().add(new THREE.Vector3(0,.86,0)),cam=g.camera.camera.clone();cam.position.copy(center).add(new THREE.Vector3(1.8,.12,2.4));cam.lookAt(center);document.querySelectorAll('body>*:not(canvas)').forEach(e=>e.style.display='none');g.renderer.render(g.park.scene,cam);const feet=g.rider.shoes.map(o=>o.position.toArray()),arms=g.rider.forearms.map(o=>o.scale.y),legs=g.rider.thighs.map(o=>o.scale.y+g.rider.shins[g.rider.thighs.indexOf(o)].scale.y);return {build,pose,feet,arms,legs,position:s.position.toArray(),mass:s.body.mass(),rootScale:g.rider.rider.scale.toArray(),helmet:g.rider.human.group.getObjectByName('Head-fitted helmet')?.userData.fit};},{build,pose});records.push(result);await page.locator('body>canvas').screenshot({path:`${folder}/${build}-${pose}.png`});assert.ok(result.arms.every(n=>Number.isFinite(n)&&n<.48));assert.deepEqual(result.rootScale,[1,1,1]);
}
for(const id of ['rider-01','rider-02','rider-03'])for(const head of ['head-helmet-red','head-cap-navy','head-beanie-black','head-none-black']){await page.evaluate(async({id,head})=>{const g=window.__LAZER;g.profile.riderId=id;g.profile.outfit.head=head;g.profile.bodyBuild='regular';g.rider.applyProfile(g.profile);await new Promise(r=>setTimeout(r,100));g.sim.reset(0,true);g.advance(.1,{},false);g.rider.update(g.sim,.1,1);const p=g.rider.root.position.clone();p.y+=1.45;const c=g.camera.camera.clone();c.position.copy(p).add(g.sim.position.clone().set(.35,.03,.72));c.lookAt(p);g.renderer.render(g.park.scene,c);},{id,head});await page.locator('body>canvas').screenshot({path:`${folder}/${id}-${head}.png`});}
writeFileSync('artifacts/fit-pass/appearance.json',JSON.stringify({records,errors},null,2));assert.equal(errors.length,0);console.log('33 body/pose combinations and 12 headwear views checked.',errors);
}finally{await browser.close();}
