import {chromium} from 'playwright';import assert from 'node:assert/strict';import {writeFileSync,mkdirSync} from 'node:fs';
// artifacts/ is gitignored, so these output directories do not exist in a fresh clone.
mkdirSync('artifacts/fit-pass/addendum',{recursive:true});
const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:1280,height:960}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5180/');await p.waitForFunction(()=>window.__LAZER?.rider.human);await p.evaluate(async()=>{window.__LAZER.testing(true);await window.__LAZER.startSession('outdoor',true);});
await p.evaluate(async()=>{const g=window.__LAZER,s=g.sim,w=g.interactions,{emptyInput}=await import('/src/input/input.ts');s.reset(0,true);s.walking=true;s.velocity.set(0,0,0);s.body.setLinvel(s.velocity,true);g.profile.pockets.entries=[];g.profile.pockets.held=null;w.vend(s,'Soda',s.position.clone());for(let i=0;i<60;i++){if(s.emote)s.emote.time+=1/60;w.update(s,emptyInput(),1/60);}w.useHeld(s);});
for(const [label,duration]of [['opening',.25],['drinking',.95],['empty-can',1.3]]){await p.evaluate(async duration=>{const g=window.__LAZER,s=g.sim,w=g.interactions,{emptyInput}=await import('/src/input/input.ts');for(let i=0;i<duration*60;i++){if(s.emote)s.emote.time+=1/60;w.update(s,emptyInput(),1/60);g.rider.update(s,1/60,1);w.render(g.rider);}const c=g.camera.camera.clone(),center=g.rider.root.position.clone();center.y+=1.13;c.position.copy(center).add(s.position.clone().set(.9,.1,1.8));c.lookAt(center);g.renderer.render(g.park.scene,c);document.querySelectorAll('body>*:not(canvas)').forEach(e=>e.style.display='none');},duration);await p.locator('body>canvas').screenshot({path:`artifacts/fit-pass/addendum/${label}.png`});}
const water=await p.evaluate(async()=>{const g=window.__LAZER,s=g.sim,w=g.interactions,{emptyInput}=await import('/src/input/input.ts'),source=w.items.find(i=>i.interactionType==='fountain').position;w.fountain(s,source);for(let i=0;i<75;i++){if(s.emote)s.emote.time+=1/60;w.update(s,emptyInput(),1/60);g.rider.update(s,1/60,1);w.render(g.rider);}const c=g.camera.camera.clone(),center=source.clone();center.y+=.9;c.position.copy(center).add(s.position.clone().set(1.7,.25,1.8));c.lookAt(center);g.renderer.render(g.park.scene,c);return w.waterActive;});assert.ok(water);await p.locator('body>canvas').screenshot({path:'artifacts/fit-pass/addendum/fountain.png'});
const cancelled=await p.evaluate(async()=>{const g=window.__LAZER,{emptyInput}=await import('/src/input/input.ts'),f=emptyInput();f.lean=-1;g.interactions.update(g.sim,f,.016);return !g.interactions.waterActive&&!g.sim.emote;});assert.ok(cancelled);
for(const [name,pos,look]of [['sign-front',[28,2.8,-32],[28,2,-44]],['sign-back',[28,2.8,-56],[28,2,-44]],['bmx-gate',[65,3.2,-34],[65,1,-22]],['ridges',[0,8,25],[0,13,135]]]){await p.evaluate(({pos,look})=>{const g=window.__LAZER,c=g.camera.camera.clone();c.position.fromArray(pos);c.lookAt(...look);g.renderer.render(g.park.scene,c);},{pos,look});await p.locator('body>canvas').screenshot({path:`artifacts/fit-pass/addendum/${name}.png`});}
const gate=await p.evaluate(()=>{const g=window.__LAZER,s=g.sim;s.reset(0,true);s.position.set(65,.22,-27);s.body.setTranslation(s.position,true);s.previousPosition.copy(s.position);s.yaw=s.previousYaw=0;s.velocity.set(0,0,4);s.body.setLinvel(s.velocity,true);g.advance(1,{},false);return {z:s.position.z,state:s.state};});assert.ok(gate.z>-24);writeFileSync('artifacts/fit-pass/addendum/world.json',JSON.stringify({water,cancelled,gate,errors},null,2));assert.equal(errors.length,0);console.log({water,cancelled,gate});
}finally{await b.close();}
