import {chromium} from 'playwright';import assert from 'node:assert/strict';import {writeFileSync,mkdirSync} from 'node:fs';
// artifacts/ is gitignored, so these output directories do not exist in a fresh clone.
mkdirSync('artifacts/complete-update',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH===undefined?'C:/Program Files/Google/Chrome/Application/chrome.exe':(process.env.CHROME_PATH||undefined),headless:true});
try{const page=await browser.newPage({viewport:{width:915,height:412},hasTouch:true,isMobile:true});await page.addInitScript(()=>{/* This suite covers the physical-controller gate; touch controls are tested separately (artifacts/claude/touch-pad.mjs). */if(!localStorage.getItem('lazer-profile-v1'))localStorage.setItem('lazer-profile-v1',JSON.stringify({version:3,settings:{touchControls:'off',controlsVersion:2}}));window.testPads=[];Object.defineProperty(navigator,'getGamepads',{value:()=>window.testPads});});await page.goto('http://127.0.0.1:5180/?map=outdoor');await page.waitForFunction(()=>window.__LAZER);await page.getByRole('button',{name:'Enable Game'}).click();await page.waitForFunction(()=>document.querySelector('#mobile-start h2')?.textContent==='CONTROLLER REQUIRED');
 const checks=['activation explains controller pairing'];const pad=(connected,mapping='standard')=>page.evaluate(({connected,mapping})=>{window.testPads=connected?[{connected:true,index:0,mapping,id:'Test standard controller',timestamp:performance.now(),axes:[0,0,0,0],buttons:Array.from({length:17},()=>({value:0,pressed:false,touched:false}))}]:[];},{connected,mapping});
 await pad(true,'');await page.waitForFunction(()=>document.querySelector('#mobile-start h2')?.textContent==='CONTROLLER NOT SUPPORTED');checks.push('nonstandard mapping explained');await pad(true);await page.waitForFunction(()=>document.querySelector('#mobile-start').hidden);
 const press=async index=>{await page.evaluate(index=>{const b=window.testPads[0].buttons[index];b.value=1;b.pressed=true;},index);await page.waitForTimeout(80);await page.evaluate(index=>{const b=window.testPads[0].buttons[index];b.value=0;b.pressed=false;},index);await page.waitForTimeout(70);};
 // Home now opens a PLAY submenu (SOLO / PRIVATE FREE-RIDE) before the park list.
 await press(0);assert.equal(await page.evaluate(()=>window.__LAZER.menu.screen),'play');checks.push('controller opens the Play menu');
 await press(0);assert.equal(await page.evaluate(()=>window.__LAZER.menu.screen),'maps');checks.push('controller reaches the park list');
 await press(13);await press(0);await page.waitForFunction(()=>window.__LAZER.hud.started);checks.push('controller starts session');
 await page.evaluate(()=>{window.testPads[0].axes[3]=1;});await page.waitForTimeout(250);await pad(false);await page.waitForFunction(()=>!document.querySelector('#mobile-start').hidden);assert.equal(await page.evaluate(()=>window.__LAZER.hud.paused),true);assert.equal(await page.evaluate(()=>window.__LAZER.sim.preload.amount),0);checks.push('disconnect pauses and clears preload');
 await pad(true);await page.waitForFunction(()=>document.querySelector('#mobile-start').hidden);assert.equal(await page.evaluate(()=>window.__LAZER.hud.paused),true);checks.push('reconnection requires deliberate resume');await page.setViewportSize({width:412,height:915});await page.waitForTimeout(100);assert.equal(await page.locator('#rotate-device').isVisible(),true);checks.push('portrait rotate guidance');
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);assert.equal(overflow,false);checks.push('portrait has no horizontal overflow');
 writeFileSync('artifacts/complete-update/mobile.json',JSON.stringify({kind:'Automated desktop Chrome with mobile viewport and simulated standard Gamepad API. NOT physical phone/Bluetooth testing.',checks},null,2));console.log(checks);
}finally{await browser.close();}
