import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';
const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:1400,height:900}});await p.goto('http://127.0.0.1:5182');await p.waitForFunction(()=>window.__LAZER?.menu.previewRider.human);mkdirSync('artifacts/sesh',{recursive:true});
// Read the palm offset from the implementation so this check cannot drift from it again.
const PALM_OFFSET=await p.evaluate(async()=>(await import('/src/scooter/assembly.ts')).GRIP_PALM_OFFSET);

const measurements=[];for(const rider of ['rider-01','rider-02','rider-03'])for(const build of ['skinny','regular','chunky']){await p.evaluate(({rider,build})=>{const g=window.__LAZER,m=g.menu;m.profile.riderId=rider;m.profile.bodyBuild=build;m.previewRider.applyProfile(m.profile);m.show('rider');m.pan.set(.3,0,0);m.focus.set(0,1.1,.2);m.focusTarget.copy(m.focus);m.zoom=m.zoomTarget=1.15;},{rider,build});await p.waitForFunction(rider=>{const h=window.__LAZER.menu.previewRider.human;return h?.id===rider&&h.materials[0].map?.image?.complete;},rider);await p.waitForTimeout(150);measurements.push(await p.evaluate(OFFSET=>{const m=window.__LAZER.menu;window.__LAZER.render();const r=m.previewRider;return {rider:m.profile.riderId,build:m.profile.bodyBuild,gaps:r.hands.map((h,i)=>{const V=h.position.constructor;return h.localToWorld(new V(0,-((h.userData.gripRadius??.0165)+OFFSET),h.userData.palmLength??.082)).distanceTo(r.assembly.gripSockets[i].getWorldPosition(new V()));})};},PALM_OFFSET));if(build==='regular')await p.screenshot({path:`artifacts/sesh/grip-${rider}.png`});}
assert(measurements.every(r=>r.gaps.every(g=>g<.001)));
const equipment=await p.evaluate(async()=>{const g=window.__LAZER;g.testing(true);await g.startSession('outdoor',true);const {loadProfile}=await import('/src/data/loadout.ts');const m=g.menu;await m.economy.setTestCredit(1000,true);const items=[{partId:'mafioso-bars-y',variantId:'mafioso_bars_y_black_gold'},{partId:'mafioso-wheels-petal',variantId:'mafioso_wheels_petal_oilslick'},{partId:'mafioso-clamp-segmented',variantId:'mafioso_clamp_segmented_chrome'}];for(const item of items){await m.economy.buy(item);await m.equip(item.partId,item.variantId);}g.advance(.1,{},true);g.render();return {saved:loadProfile().scooter,actual:g.rider.assembly.root.userData.loadout,profile:g.profile.scooter};});assert.deepEqual(equipment.saved,equipment.actual);assert.deepEqual(equipment.saved,equipment.profile);
await p.evaluate(()=>{const g=window.__LAZER;g.hud.setPaused(true);document.querySelector('[data-action="map"]').click();g.render();});await p.screenshot({path:'artifacts/sesh/maps.png'});writeFileSync('artifacts/sesh/verification.json',JSON.stringify({measurements,equipment},null,2));console.log('9 preview fits and Mafioso bars/wheels/clamp persistence passed');}finally{await b.close();}
