import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{const page=await browser.newPage({viewport:{width:1400,height:950}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5180/?map=outdoor');await page.waitForFunction(()=>window.__LAZER?.rider.human);
 const results=await page.evaluate(async()=>{const g=window.__LAZER;g.testing(true);await g.menu.onRide('techno_gravity');g.advance(.25,{},true);const checks=[];const check=(label,ok)=>checks.push({label,ok:!!ok});check('shop map selected',location.search.includes('techno_gravity'));check('shop spawn',Math.abs(g.sim.position.z+11)<1);check('DIY rails exist',g.park.rails.length>=5);
 const {loadProfile}=await import('/src/data/loadout.ts');await g.menu.economy.reward('browser-shop-bank',10000);g.menu.openShop('bars');check('display opens the brand page for its category',g.menu.screen==='brand-items'&&g.menu.browseBrand==='mafioso');check('shop lists only parts not owned',g.menu.choices.filter(c=>c.cell).length===3);g.menu.index=0;g.menu.select();check('confirmation required',g.menu.screen==='purchase');const before=loadProfile().wallet.credit;g.menu.index=0;g.menu.select();g.menu.select();await new Promise(r=>setTimeout(r,50));check('one purchase',loadProfile().wallet.credit===before-75);check('equip or keep offered',g.menu.screen==='purchased');check('bought colourway leaves the shop list',(g.menu.show('brand-items'),g.menu.choices.filter(c=>c.cell).length===2));g.menu.show('purchased');g.menu.index=0;g.menu.select();await new Promise(r=>setTimeout(r,300));/* equip saves asynchronously */check('correct equipped variant',g.profile.scooter.bars.variantId==='mafioso_bars_y_black_gold');g.menu.shopOpen=false;g.menu.root.hidden=true;
 const pos=g.sim.position;pos.set(0,.35,-6);g.sim.body.setTranslation(pos,true);g.sim.walking=true;g.sim.yaw=0;for(let i=0;i<240;i++)g.advance(1/120,{lean:-1},false);check('door physically walkable',g.sim.position.z>-4.5);
 await g.menu.onRide('outdoor');check('parts persist across maps',g.profile.scooter.bars.partId==='mafioso-bars-y');await g.menu.onRide('techno_gravity');check('parts persist reload data',loadProfile().scooter.bars.partId==='mafioso-bars-y');g.advance(.1,{},true);return checks;});
 mkdirSync('artifacts/complete-update/shop',{recursive:true});for(const [name,pos,target]of [['front',[16,9,-22],[0,1,-2]],['inside',[0,2.3,-3],[0,1.4,5]],['alley',[18,14,38],[0,1,24]]]){await page.evaluate(({pos,target})=>{const g=window.__LAZER;const c=g.camera.camera.clone();c.position.set(...pos);c.lookAt(...target);document.querySelectorAll('body>*:not(canvas)').forEach(e=>e.style.display='none');g.renderer.render(g.rider.root.parent,c);},{pos,target});await page.locator('body>canvas').screenshot({path:`artifacts/complete-update/shop/${name}.png`});}
 writeFileSync('artifacts/complete-update/shop/results.json',JSON.stringify({results,errors},null,2));console.log(results,errors);assert.ok(results.every(r=>r.ok));assert.equal(errors.length,0);
}finally{await browser.close();}
