// Sesh Music: the one owner of personal soundtrack playback.
//
// Lives for the whole app, outside maps and menus. The phone panel only observes
// and controls it. Playback streams through a single HTMLAudioElement (never
// decoded into memory, never positional) whose volume is the music volume
// multiplied by the game's Sound switch. Catalog: public/music/catalog.json,
// generated by `npm run music:sync` (see docs/MUSIC_SETUP.md).

export interface MusicTrack {
  id: string;
  title: string;
  artist: string;
  file: string;
  cover?: string;
  credit?: string;
}
export type MusicStatus = "empty" | "idle" | "loading" | "playing" | "paused" | "blocked" | "error";
export type RepeatMode = "off" | "all" | "one";
export interface MusicSettings {
  enabled: boolean;
  volume: number; // 0..1, music only
  muted: boolean;
  shuffle: boolean;
  repeat: RepeatMode;
  resumeOnEnter: boolean;
  pauseWhenHidden: boolean;
  notifications: boolean;
}
interface SavedMusic extends MusicSettings {
  trackId: string | null;
  position: number;
}

const STORAGE_KEY = "swf-music-v1";
const DEFAULTS: SavedMusic = {
  enabled: true,
  volume: 0.6,
  muted: false,
  shuffle: false,
  repeat: "all",
  resumeOnEnter: false,
  pauseWhenHidden: true,
  notifications: true,
  trackId: null,
  position: 0,
};
// Skipping between tracks fades the outgoing song out and the incoming one in.
const TRACK_FADE_OUT = 0.6;
const TRACK_FADE_IN = 0.9;
const RESUME_FADE_IN = 0.25;
const clamp01 = (v: number) => Math.min(1, Math.max(0, v));

function loadSaved(): SavedMusic {
  try {
    const raw = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? "null");
    if (!raw || typeof raw !== "object") return { ...DEFAULTS };
    const bool = (k: keyof MusicSettings) => (typeof raw[k] === "boolean" ? raw[k] : DEFAULTS[k]) as boolean;
    return {
      enabled: bool("enabled"),
      volume: Number.isFinite(raw.volume) ? clamp01(raw.volume) : DEFAULTS.volume,
      muted: bool("muted"),
      shuffle: bool("shuffle"),
      repeat: ["off", "all", "one"].includes(raw.repeat) ? raw.repeat : DEFAULTS.repeat,
      resumeOnEnter: bool("resumeOnEnter"),
      pauseWhenHidden: bool("pauseWhenHidden"),
      notifications: bool("notifications"),
      trackId: typeof raw.trackId === "string" ? raw.trackId : null,
      position: Number.isFinite(raw.position) && raw.position > 0 ? raw.position : 0,
    };
  } catch {
    return { ...DEFAULTS };
  }
}

export class MusicService {
  tracks: MusicTrack[] = [];
  settings: MusicSettings;
  status: MusicStatus = "idle";
  current: MusicTrack | null = null;
  errorMessage = "";
  /** The player asked for music to be playing. Separate from browser suspension. */
  wantsPlay = false;
  catalogLoaded = false;
  catalogError = "";
  readonly unavailable = new Set<string>();
  private audio: HTMLAudioElement;
  private soundEnabled = true;
  private history: string[] = [];
  private queue: string[] = [];
  private loadToken = 0;
  private failures = 0;
  private fade = 1;
  private fadeTimer = 0;
  private savedPosition = 0;
  private lastSave = 0;
  private hiddenPaused = false;
  private listeners = new Set<() => void>();
  onNowPlaying: (track: MusicTrack) => void = () => {};

  constructor() {
    const saved = loadSaved();
    const { trackId, position, ...settings } = saved;
    this.settings = settings;
    this.savedPosition = position;
    this.audio = new Audio();
    this.audio.preload = "none";
    const a = this.audio;
    a.addEventListener("playing", () => this.setStatus("playing"));
    a.addEventListener("pause", () => { if (this.status === "playing") this.setStatus("paused"); });
    a.addEventListener("waiting", () => { if (this.wantsPlay) this.setStatus("loading"); });
    a.addEventListener("timeupdate", () => this.persist(false));
    a.addEventListener("durationchange", () => this.emit());
    a.addEventListener("ended", () => this.trackEnded());
    a.addEventListener("error", () => this.trackFailed("This track could not be played."));
    document.addEventListener("visibilitychange", () => this.visibility());
    this.pendingTrackId = trackId;
  }
  private pendingTrackId: string | null;

  // ---- Catalog ------------------------------------------------------------------
  async loadCatalog(url = "/music/catalog.json") {
    try {
      const response = await fetch(url, { cache: "no-cache" });
      const type = response.headers.get("content-type") ?? "";
      if (!response.ok || type.includes("text/html")) throw new Error("catalog not found");
      const data = await response.json();
      const list = Array.isArray(data?.tracks) ? data.tracks : [];
      const seen = new Set<string>();
      this.tracks = list.filter((t: MusicTrack) =>
        t && typeof t.id === "string" && typeof t.file === "string" && t.file.startsWith("/music/tracks/") &&
        !seen.has(t.id) && seen.add(t.id))
        .map((t: MusicTrack) => ({
          id: t.id,
          title: String(t.title ?? t.id),
          artist: String(t.artist ?? ""),
          file: t.file,
          ...(typeof t.cover === "string" && t.cover.startsWith("/music/covers/") ? { cover: t.cover } : {}),
          ...(typeof t.credit === "string" ? { credit: t.credit } : {}),
        }));
      this.catalogError = "";
    } catch {
      this.tracks = [];
      this.catalogError = "Music catalog unavailable.";
    }
    this.catalogLoaded = true;
    this.rebuildQueue();
    // A saved track that was removed falls back to the first track, paused.
    const restored = this.tracks.find((t) => t.id === this.pendingTrackId) ?? null;
    this.current = restored ?? this.tracks[0] ?? null;
    if (!restored) this.savedPosition = 0;
    this.status = this.tracks.length ? "idle" : "empty";
    this.emit();
  }

  // ---- Observers --------------------------------------------------------------------
  subscribe(fn: () => void) {
    this.listeners.add(fn);
    return () => this.listeners.delete(fn);
  }
  private emit() {
    this.listeners.forEach((fn) => fn());
  }
  private setStatus(status: MusicStatus) {
    if (this.status === status) return;
    this.status = status;
    if (status === "playing") this.failures = 0;
    this.emit();
  }
  get position() {
    return this.audio.currentTime || (this.current && this.audio.src === "" ? this.savedPosition : 0);
  }
  get duration() {
    return Number.isFinite(this.audio.duration) ? this.audio.duration : 0;
  }

  // ---- Volume ------------------------------------------------------------------------
  /** The game's Sound switch (master on/off). Music obeys it without its own copy. */
  setSoundEnabled(enabled: boolean) {
    this.soundEnabled = enabled;
    this.applyVolume();
  }
  setVolume(volume: number) {
    this.settings.volume = clamp01(Math.round(volume * 100) / 100);
    if (this.settings.volume > 0) this.settings.muted = false;
    this.applyVolume();
    this.persist(true);
    this.emit();
  }
  toggleMute() {
    this.settings.muted = !this.settings.muted;
    this.applyVolume();
    this.persist(true);
    this.emit();
  }
  private applyVolume() {
    const on = this.soundEnabled && this.settings.enabled && !this.settings.muted;
    this.audio.volume = on ? clamp01(this.settings.volume * this.fade) : 0;
  }
  private fadeTo(target: number, seconds: number) {
    return new Promise<void>((done) => {
      clearInterval(this.fadeTimer);
      const start = this.fade, began = performance.now();
      if (seconds <= 0 || document.hidden) { this.fade = target; this.applyVolume(); return done(); }
      this.fadeTimer = window.setInterval(() => {
        const t = Math.min(1, (performance.now() - began) / (seconds * 1000));
        this.fade = start + (target - start) * t;
        this.applyVolume();
        if (t >= 1) { clearInterval(this.fadeTimer); done(); }
      }, 30);
    });
  }

  // ---- Settings -----------------------------------------------------------------------
  setSetting<K extends keyof MusicSettings>(key: K, value: MusicSettings[K]) {
    this.settings[key] = value;
    if (key === "enabled" && !value) this.pause();
    if (key === "shuffle") this.rebuildQueue();
    this.applyVolume();
    this.persist(true);
    this.emit();
  }
  cycleRepeat() {
    const order: RepeatMode[] = ["off", "all", "one"];
    this.setSetting("repeat", order[(order.indexOf(this.settings.repeat) + 1) % order.length]);
  }

  // ---- Transport -------------------------------------------------------------------
  /** Called from a user gesture (click, key or button press). */
  async play() {
    if (!this.current) return;
    if (!this.settings.enabled) this.setSetting("enabled", true);
    this.wantsPlay = true;
    this.hiddenPaused = false;
    if (!this.audio.src || !this.audio.src.endsWith(this.current.file)) await this.load(this.current, this.savedPosition);
    else await this.start(this.loadToken);
  }
  async pause() {
    this.wantsPlay = false;
    this.hiddenPaused = false;
    this.audio.pause();
    if (this.current) this.setStatus(this.audio.src ? "paused" : "idle");
    this.persist(true);
  }
  togglePlay() {
    return this.status === "playing" || this.status === "loading" ? this.pause() : this.play();
  }
  /** Picking the track already playing leaves it playing. */
  select(id: string) {
    const track = this.tracks.find((t) => t.id === id);
    if (!track) return;
    if (this.current?.id === id && this.audio.src) {
      if (this.status !== "playing") void this.play();
      return;
    }
    this.pushHistory();
    this.wantsPlay = true;
    void this.load(track, 0);
  }
  next(manual = true) {
    const id = this.nextId(manual);
    if (!id) {
      this.wantsPlay = false;
      this.audio.pause();
      if (this.audio.src) this.audio.currentTime = 0;
      this.setStatus("paused");
      return;
    }
    this.pushHistory();
    this.wantsPlay = true;
    void this.load(this.tracks.find((t) => t.id === id)!, 0);
  }
  previous(): void {
    if (this.audio.currentTime > 3 || !this.history.length) {
      const token = this.loadToken;
      if (this.status === "playing")
        void this.fadeTo(0, TRACK_FADE_OUT).then(() => {
          if (token !== this.loadToken) return;
          this.seek(0);
          void this.fadeTo(1, TRACK_FADE_IN);
        });
      else {
        this.seek(0);
        if (this.wantsPlay) void this.play();
      }
      return;
    }
    const id = this.history.pop()!;
    const track = this.tracks.find((t) => t.id === id);
    if (!track) return this.previous();
    this.wantsPlay = true;
    void this.load(track, 0);
  }
  seek(seconds: number) {
    if (!this.current) return;
    if (!this.audio.src) {
      this.savedPosition = Math.max(0, seconds);
      this.emit();
      return;
    }
    const end = this.duration || Infinity;
    this.audio.currentTime = Math.min(Math.max(0, seconds), Math.max(0, end - 0.25));
    this.persist(true);
    this.emit();
  }

  private pushHistory() {
    if (!this.current) return;
    this.history.push(this.current.id);
    if (this.history.length > 100) this.history.shift();
  }
  private playable() {
    return this.tracks.filter((t) => !this.unavailable.has(t.id));
  }
  private rebuildQueue() {
    const ids = this.tracks.map((t) => t.id);
    if (this.settings.shuffle) {
      for (let i = ids.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [ids[i], ids[j]] = [ids[j], ids[i]];
      }
      // Keep the current track at the head so shuffle continues from here.
      const at = this.current ? ids.indexOf(this.current.id) : -1;
      if (at > 0) ids.unshift(...ids.splice(at, 1));
    }
    this.queue = ids;
  }
  private nextId(manual: boolean): string | null {
    const usable = new Set(this.playable().map((t) => t.id));
    if (!usable.size) return null;
    if (!manual && this.settings.repeat === "one" && this.current && usable.has(this.current.id)) return this.current.id;
    let index = this.current ? this.queue.indexOf(this.current.id) : -1;
    for (let step = 0; step < this.queue.length; step++) {
      index++;
      if (index >= this.queue.length) {
        if (!manual && this.settings.repeat === "off") return null;
        if (this.settings.shuffle) {
          const last = this.current?.id;
          this.rebuildQueue();
          // Avoid the same song twice in a row across a reshuffle.
          if (this.queue.length > 1 && this.queue[0] === last) this.queue.push(this.queue.shift()!);
        }
        index = 0;
      }
      const id = this.queue[index];
      if (usable.has(id)) return id;
    }
    return null;
  }

  private async load(track: MusicTrack, position: number) {
    const token = ++this.loadToken;
    const switching = !!this.audio.src && this.status === "playing";
    if (switching) await this.fadeTo(0, TRACK_FADE_OUT);
    if (token !== this.loadToken) return;
    this.current = track;
    this.errorMessage = "";
    this.savedPosition = 0;
    this.setStatus("loading");
    this.emit();
    this.audio.src = track.file;
    this.audio.preload = "auto";
    if (position > 0) {
      const at = position;
      this.audio.addEventListener("loadedmetadata", () => {
        if (token === this.loadToken && Number.isFinite(this.audio.duration) && at < this.audio.duration - 1) this.audio.currentTime = at;
      }, { once: true });
    }
    this.persist(true);
    if (this.settings.notifications) this.onNowPlaying(track);
    await this.start(token, TRACK_FADE_IN);
  }
  private async start(token: number, fadeIn = RESUME_FADE_IN) {
    if (!this.wantsPlay || !this.current) return;
    this.fade = 0;
    this.applyVolume();
    try {
      await this.audio.play();
      if (token !== this.loadToken) return;
      void this.fadeTo(1, fadeIn);
    } catch (error) {
      if (token !== this.loadToken) return;
      const name = (error as DOMException)?.name;
      if (name === "NotAllowedError") {
        // The browser wants a click/tap first. Keep the intent; the panel shows a
        // clear enable action and nothing retries on its own.
        this.fade = 1;
        this.applyVolume();
        this.setStatus("blocked");
      } else if (name !== "AbortError") this.trackFailed("This track could not be played.");
    }
  }
  private trackEnded() {
    this.persist(true);
    if (this.settings.repeat === "one" && this.current) {
      this.audio.currentTime = 0;
      void this.start(this.loadToken);
      return;
    }
    this.next(false);
  }
  private trackFailed(message: string) {
    if (!this.current || !this.audio.src) return;
    this.unavailable.add(this.current.id);
    this.errorMessage = message;
    this.setStatus("error");
    this.failures++;
    // Skip to the next working track, but never loop forever over a broken library.
    if (this.wantsPlay && this.failures < this.tracks.length && this.playable().length) this.next(false);
    else this.wantsPlay = false;
  }
  private visibility() {
    if (document.hidden) {
      if (this.settings.pauseWhenHidden && this.status === "playing") {
        this.audio.pause();
        this.hiddenPaused = true;
      }
    } else if (this.hiddenPaused) {
      // Resume only what the tab switch paused, never a pause the player chose.
      this.hiddenPaused = false;
      if (this.wantsPlay) void this.start(this.loadToken);
    }
  }
  /** Entering a Sesh: resume only when the setting asks for it. */
  enterGame() {
    if (this.settings.resumeOnEnter && this.settings.enabled && this.current && this.status !== "playing") void this.play();
  }

  // ---- Persistence (throttled) ---------------------------------------------------
  private persist(force: boolean) {
    const now = performance.now();
    if (!force && now - this.lastSave < 5000) return;
    this.lastSave = now;
    const data: SavedMusic = {
      ...this.settings,
      trackId: this.current?.id ?? null,
      position: this.audio.src ? this.audio.currentTime || 0 : this.savedPosition,
    };
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
    } catch {
      // Storage unavailable: playback carries on without saving.
    }
  }
}

export const music = new MusicService();
