export const TUNE = {
  // Begin clearing coping before the rider reaches its collision capsule.
  // A wider handoff keeps a smooth transition at real riding speeds.
  transitionLipReleaseDistance: 0.65,
  transitionRailClearTime: 0.18,
  quarterOverDeckSpeed: 12,
  reentryCaptureStrength: 0.24,
  caseHardImpact: 8.2,
  step: 1 / 120,
  markerHoldDuration: 0.75,
  airWeightShiftStrength: 0.29,
  airWeightShiftResponse: 8,
  airPitchBiasMax: 0.88,
  airPitchBiasAcceleration: 18,
  airPitchBiasSpeed: 3.2,
  airTrajectoryInfluence: 0.3,
  airTrajectoryBudget: 0.4,
  airWeightRecentering: 4,
  airEntryPitchDecay: 1.1,
  rampLaunchLeanAngle: 0.85,
  gravity: 15,
  radius: 0.22,
  push: 2.5,
  pushCadence: 0.46,
  pushHoldDelay: 0.17,
  maxSpeed: 12,
  rollingDrag: 0.1,
  crouchFastDragMultiplier: 0.72,
  crouchDownhillGain: 0.5,
  brake: 7.5,
  copingStallBrake: 11,
  copingStallSettleSpeed: 2.7,
  steering: 2.7,
  carveGrip: 8,
  steeringResponse: 8,
  airAcceleration: 24,
  airMaxSpin: 12,
  airDamping: 0.48,
  fakieMinSpeed: 0.8,
  fakieRevertThreshold: 0.68,
  fakieRevertHold: 0.12,
  fakieRevertSpeed: 4.8,
  fakieRevertAcceleration: 18,
  lowAirSpinMultiplier: 0.82,
  highAirSpinMultiplier: 1,
  spinStickDeadzone: 0.025,
  spinResponseExponent: 1.35,
  spinCeilingExponent: 0.8,
  spinAccelerationFloor: 0.35,
  spinLowAirtime: 0.55,
  spinHighAirtime: 1.35,
  stationaryCameraFollowThreshold: 1.2,
  cameraFullFollowSpeed: 3,
  railImpactBailSpeed: 4.5,
  railImpactWobbleSpeed: 0.7,
  railCollisionImpulseScale: 0.22,
  railImpactCooldown: 0.45,
  rampLeanResponse: 9,
  rampLeanAngle: 0.28,
  rampLeanLookAhead: 1.1,
  rampLeanCenterOfMassDrop: 0.12,
  // Assist settles a committed grind, it never pulls a rider across a rail.
  grindSettleTime: 0.28,
  grindLateralSpring: 28,
  grindLateralDamping: 9,
  grindSteering: 1.1,
  fakiePointsPerSecond: 30,
  fakieEntryPoints: 50,
  rotationPointsPer180: 100,
  deckTurnPoints: 150,
  barTurnPoints: 100,
  bodyTrickPoints: 100,
  contactTrickPoints: 75,
  hopMin: 3.7,
  hopMax: 7.2,
  preloadTime: 0.48,
  coyoteTime: 0.09,
  hopBuffer: 0.12,
  deckAcceleration: 170,
  deckMaxSpeed: 21,
  barAcceleration: 220,
  barMaxSpeed: 26,
  cleanAngle: 0.3,
  sketchAngle: 0.9,
  failAngle: 1.3,
  cleanImpact: 9.5,
  failImpact: 16,
  cleanPartAngle: 0.32,
  failPartAngle: 1.25,
  recoveryTime: 1.05,
  grindDistance: 0.18,
  grindIntentDistance: 0.38,
  grindCaptureHeight: 0.38,
  grindApproachAlignment: 0.86,
  grindIntentAlignment: 0.72,
  grindExactDistance: 0.055,
  grindNaturalIntentScore: 0.93,
  grindHeldIntentScore: 0.6,
  grindStrength: 48,
  grindMinSpeed: 1.5,
  manualSensitivity: 2.8,
  manualStability: 1.7,
  walkSpeed: 3.2,
  runSpeed: 6.4,
  runMountBoost: 0.9,
  trickHoldDelay: 0.18,
  bumperHoldThreshold: 0.18,
  walkAcceleration: 9,
  walkTurnResponse: 10,
  pumpGain: 1.5,
  pumpCooldown: 0.38,
  comboTimeout: 3,
  repetitionValues: [1, .75, .5, .35],
  comboStep: .25,
  comboCap: 4,
  firstSpinThreshold: 75,
  spinNameTolerance: 20,
  manualMin: .2,
  manualMax: .5,
  manualDwell: .14,
  preloadThreshold: .65,
  rumble: { pop: 0.12, clean: 0.2, sketchy: 0.38, bail: 0.6 },
} as const;
export const TAU = Math.PI * 2;
export const clamp = (x: number, a: number, b: number) =>
  Math.max(a, Math.min(b, x));
export const damp = (a: number, b: number, k: number, dt: number) =>
  a + (b - a) * (1 - Math.exp(-k * dt));
export const wrap = (a: number) => Math.atan2(Math.sin(a), Math.cos(a));
